package lineage.export;

/**
 * HTML 导出器。
 *
 * 生成的页面会在浏览器中读取同目录的 graph.json 并渲染图谱。
 */
public final class HtmlGraphExporter {
    private HtmlGraphExporter() {
    }

    /**
     * 导出静态 HTML 模板。
     */
    public static String export() {
        return "<!doctype html>\n"
                + "<html lang=\"zh-CN\">\n"
                + "<head>\n"
                + "  <meta charset=\"UTF-8\" />\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <title>Lineage Graph</title>\n"
                + "  <style>\n"
                + "    body { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Arial, sans-serif; margin: 0; background: #f8fafc; color: #111827; }\n"
                + "    .wrap { max-width: 1200px; margin: 24px auto; padding: 0 16px; }\n"
                + "    h1 { margin: 0 0 12px; font-size: 22px; }\n"
                + "    .card { background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; margin-bottom: 16px; }\n"
                + "    .legend { display: flex; flex-wrap: wrap; gap: 16px; font-size: 13px; }\n"
                + "    .dot { width: 10px; height: 10px; border-radius: 999px; display: inline-block; margin-right: 6px; vertical-align: middle; }\n"
                + "    .svg-box { overflow: auto; border: 1px solid #e5e7eb; border-radius: 8px; background: #ffffff; }\n"
                + "    svg { width: 100%; min-width: 980px; height: 680px; display: block; }\n"
                + "    .node-label { font-size: 12px; fill: #111827; }\n"
                + "    .edge-label { font-size: 11px; fill: #374151; }\n"
                + "    table { width: 100%; border-collapse: collapse; font-size: 13px; }\n"
                + "    th, td { border-bottom: 1px solid #e5e7eb; text-align: left; padding: 8px 6px; }\n"
                + "    th { background: #f9fafb; }\n"
                + "    .muted { color: #6b7280; font-size: 12px; }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "<div class=\"wrap\">\n"
                + "  <h1>业务关系图谱（graph.json）</h1>\n"
                + "\n"
                + "  <div class=\"card legend\">\n"
                + "    <div><span class=\"dot\" style=\"background:#2563eb\"></span>OPERATION</div>\n"
                + "    <div><span class=\"dot\" style=\"background:#059669\"></span>EVENT</div>\n"
                + "    <div><span class=\"dot\" style=\"background:#7c3aed\"></span>RESOURCE</div>\n"
                + "    <div><span style=\"border-bottom:2px solid #1d4ed8;display:inline-block;width:22px;vertical-align:middle;margin-right:6px\"></span>PRECEDES</div>\n"
                + "    <div><span style=\"border-bottom:2px dashed #dc2626;display:inline-block;width:22px;vertical-align:middle;margin-right:6px\"></span>MUTEX</div>\n"
                + "    <div><span style=\"border-bottom:1px dashed #6b7280;display:inline-block;width:22px;vertical-align:middle;margin-right:6px\"></span>EMITS / CONSUMES / TOUCHES</div>\n"
                + "  </div>\n"
                + "\n"
                + "  <div class=\"card svg-box\">\n"
                + "    <svg id=\"graph\" viewBox=\"0 0 1200 680\" aria-label=\"lineage graph\"></svg>\n"
                + "  </div>\n"
                + "\n"
                + "  <div class=\"card\">\n"
                + "    <div class=\"muted\" id=\"summary\"></div>\n"
                + "    <table>\n"
                + "      <thead>\n"
                + "      <tr>\n"
                + "        <th>from</th>\n"
                + "        <th>to</th>\n"
                + "        <th>type</th>\n"
                + "        <th>confidence</th>\n"
                + "        <th>evidence</th>\n"
                + "      </tr>\n"
                + "      </thead>\n"
                + "      <tbody id=\"edgeRows\"></tbody>\n"
                + "    </table>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<script>\n"
                + "(async function render() {\n"
                + "  const res = await fetch('./graph.json');\n"
                + "  if (!res.ok) {\n"
                + "    document.body.innerHTML = '<div style=\"padding:20px\">读取 graph.json 失败</div>';\n"
                + "    return;\n"
                + "  }\n"
                + "  const data = await res.json();\n"
                + "  const nodes = data.nodes || [];\n"
                + "  const edges = data.edges || [];\n"
                + "\n"
                + "  const svg = document.getElementById('graph');\n"
                + "  const NS = 'http://www.w3.org/2000/svg';\n"
                + "\n"
                + "  const nodeColor = (type) => {\n"
                + "    if (type === 'OPERATION') return '#2563eb';\n"
                + "    if (type === 'EVENT') return '#059669';\n"
                + "    if (type === 'RESOURCE') return '#7c3aed';\n"
                + "    return '#6b7280';\n"
                + "  };\n"
                + "\n"
                + "  const edgeStyle = (type) => {\n"
                + "    if (type === 'PRECEDES') return { color: '#1d4ed8', width: 2, dash: '' };\n"
                + "    if (type === 'MUTEX') return { color: '#dc2626', width: 2, dash: '8 6' };\n"
                + "    return { color: '#6b7280', width: 1.4, dash: '5 5' };\n"
                + "  };\n"
                + "\n"
                + "  const cx = 600, cy = 340, r = 250;\n"
                + "  const pos = new Map();\n"
                + "  nodes.forEach((n, i) => {\n"
                + "    const a = (Math.PI * 2 * i) / Math.max(nodes.length, 1) - Math.PI / 2;\n"
                + "    pos.set(n.id, { x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) });\n"
                + "  });\n"
                + "\n"
                + "  const defs = document.createElementNS(NS, 'defs');\n"
                + "  const marker = document.createElementNS(NS, 'marker');\n"
                + "  marker.setAttribute('id', 'arrow');\n"
                + "  marker.setAttribute('viewBox', '0 0 10 10');\n"
                + "  marker.setAttribute('refX', '9');\n"
                + "  marker.setAttribute('refY', '5');\n"
                + "  marker.setAttribute('markerWidth', '8');\n"
                + "  marker.setAttribute('markerHeight', '8');\n"
                + "  marker.setAttribute('orient', 'auto-start-reverse');\n"
                + "  const markerPath = document.createElementNS(NS, 'path');\n"
                + "  markerPath.setAttribute('d', 'M 0 0 L 10 5 L 0 10 z');\n"
                + "  markerPath.setAttribute('fill', '#374151');\n"
                + "  marker.appendChild(markerPath);\n"
                + "  defs.appendChild(marker);\n"
                + "  svg.appendChild(defs);\n"
                + "\n"
                + "  edges.forEach((e) => {\n"
                + "    const from = pos.get(e.from);\n"
                + "    const to = pos.get(e.to);\n"
                + "    if (!from || !to) return;\n"
                + "\n"
                + "    const style = edgeStyle(e.type);\n"
                + "    const line = document.createElementNS(NS, 'line');\n"
                + "    line.setAttribute('x1', from.x);\n"
                + "    line.setAttribute('y1', from.y);\n"
                + "    line.setAttribute('x2', to.x);\n"
                + "    line.setAttribute('y2', to.y);\n"
                + "    line.setAttribute('stroke', style.color);\n"
                + "    line.setAttribute('stroke-width', style.width);\n"
                + "    if (style.dash) line.setAttribute('stroke-dasharray', style.dash);\n"
                + "    if (e.type !== 'MUTEX') line.setAttribute('marker-end', 'url(#arrow)');\n"
                + "    svg.appendChild(line);\n"
                + "\n"
                + "    const midX = (from.x + to.x) / 2;\n"
                + "    const midY = (from.y + to.y) / 2;\n"
                + "    const txt = document.createElementNS(NS, 'text');\n"
                + "    txt.setAttribute('x', midX + 4);\n"
                + "    txt.setAttribute('y', midY - 4);\n"
                + "    txt.setAttribute('class', 'edge-label');\n"
                + "    txt.textContent = e.type;\n"
                + "    svg.appendChild(txt);\n"
                + "  });\n"
                + "\n"
                + "  nodes.forEach((n) => {\n"
                + "    const p = pos.get(n.id);\n"
                + "    const g = document.createElementNS(NS, 'g');\n"
                + "\n"
                + "    const c = document.createElementNS(NS, 'circle');\n"
                + "    c.setAttribute('cx', p.x);\n"
                + "    c.setAttribute('cy', p.y);\n"
                + "    c.setAttribute('r', '24');\n"
                + "    c.setAttribute('fill', nodeColor(n.type));\n"
                + "    c.setAttribute('opacity', '0.92');\n"
                + "\n"
                + "    const label = document.createElementNS(NS, 'text');\n"
                + "    label.setAttribute('x', p.x);\n"
                + "    label.setAttribute('y', p.y + 42);\n"
                + "    label.setAttribute('text-anchor', 'middle');\n"
                + "    label.setAttribute('class', 'node-label');\n"
                + "    label.textContent = `${n.name} (${n.type})`;\n"
                + "\n"
                + "    g.appendChild(c);\n"
                + "    g.appendChild(label);\n"
                + "    svg.appendChild(g);\n"
                + "  });\n"
                + "\n"
                + "  const summary = document.getElementById('summary');\n"
                + "  summary.textContent = `节点 ${nodes.length} 个，边 ${edges.length} 条`;\n"
                + "\n"
                + "  const rows = document.getElementById('edgeRows');\n"
                + "  edges.forEach((e) => {\n"
                + "    const tr = document.createElement('tr');\n"
                + "    tr.innerHTML = `<td>${e.from}</td><td>${e.to}</td><td>${e.type}</td><td>${e.confidence ?? ''}</td><td>${e.evidence ?? ''}</td>`;\n"
                + "    rows.appendChild(tr);\n"
                + "  });\n"
                + "})();\n"
                + "</script>\n"
                + "</body>\n"
                + "</html>\n";
    }
}
